"""
creates an yaml with empty values and strings from a list as its keys.
the values in the resulting yaml file can be filled out manually 
with new instrument classes to create a mapping file
"""
import yaml

# raw slakh tags
#classes = ['Synth Strings 1', 'Harpsichord', 'Slap Bass 2', 'Clarinet', 'FX 8 (sci-fi)', 'Bag pipe', 'Overdriven Guitar', 'Reed Organ', 'Telephone Ring', 'Flute', 'Brass Section', 'FX 4 (atmosphere)', 'Shamisen', 'Synth Drum', 'Blown Bottle', 'Tuba', 'Guitar harmonics', 'Shakuhachi', 'Tango Accordion', 'Pizzicato Strings', 'Recorder', 'Synth Strings 2', 'Trombone', 'Electric Piano 2', 'Viola', 'Acoustic Grand Piano', 'Piccolo', 'Music Box', 'Breath Noise', 'Electric Guitar (jazz)', 'Lead 8 (bass + lead)', 'Electric Guitar (muted)', 'Pad 2 (warm)', 'Banjo', 'Orchestral Harp', 'Timpani', 'Electric Bass (finger)', 'Ocarina', 'Electric Guitar (clean)', 'Synth Bass 1', 'Orchestra Hit', 'Pad 6 (metallic)', 'Agogo', 'FX 3 (crystal)', 'Choir Aahs', 'FX 1 (rain)', 'Clavinet', 'Xylophone', 'Accordion', 'Contrabass', 'Muted Trumpet', 'FX 6 (goblins)', 'FX 2 (soundtrack)', 'Honky-tonk Piano', 'Drums', 'Fiddle', 'Electric Grand Piano', 'Pad 8 (sweep)', 'Bassoon', 'Glockenspiel', 'Helicopter', 'Acoustic Bass', 'Taiko Drum', 'Voice Oohs', 'Applause', 'Kalimba', 'Soprano Sax', 'Distortion Guitar', 'Melodic Tom', 'Church Organ', 'Gunshot', 'Woodblock', 'Synth Bass 2', 'Koto', 'String Ensemble 1', 'Guitar Fret Noise', 'Percussive Organ', 'Slap Bass 1', 'Lead 2 (sawtooth)', 'Baritone Sax', 'English Horn', 'Alto Sax', 'Marimba', 'Violin', 'Steel Drums', 'Drawbar Organ', 'Whistle', 'Harmonica', 'Seashore', 'Pad 7 (halo)', 'Bird Tweet', 'Lead 1 (square)', 'Tinkle Bell', 'Tenor Sax', 'Acoustic Guitar (nylon)', 'Synth Brass 1', 'Bright Acoustic Piano', 'Tubular Bells', 'Electric Bass (pick)', 'Pad 3 (polysynth)', 'Trumpet', 'Lead 5 (charang)', 'Lead 4 (chiff)', 'Fretless Bass', 'Celesta', 'Reverse Cymbal', 'Lead 6 (voice)', 'Dulcimer', 'FX 5 (brightness)', 'Electric Piano 1', 'Pad 5 (bowed)', 'Acoustic Guitar (steel)', 'Pad 1 (new age)', 'FX 7 (echoes)', 'Cello', 'Tremolo Strings', 'Lead 7 (fifths)', 'Sitar', 'Oboe', 'Rock Organ', 'French Horn', 'Vibraphone', 'Synth Voice', 'Shanai', 'Lead 3 (calliope)', 'Pan Flute', 'String Ensemble 2', 'Synth Brass 2', 'Pad 4 (choir)']

# raw medleydb(1+2) tags
#classes = ['electric bass', 'flute section', 'double bass', 'trumpet', 'darbuka', 'trombone', 'male singer', 'lap steel guitar', 'trumpet section', 'gu', 'baritone saxophone', 'vibraphone', 'male speaker', 'drum set', 'harp', 'drum machine', 'fx/processed sound', 'snare drum', 'piano', 'shaker', 'harmonica', 'accordion', 'tabla', 'female singer', 'piccolo', 'scratches', 'male rapper', 'trombone section', 'clean electric guitar', 'sampler', 'melodica', 'violin', 'french horn', 'soprano saxophone', 'dizi', 'flute', 'timpani', 'viola', 'tenor saxophone', 'tuba', 'gong', 'synthesizer', 'liuqin', 'tambourine', 'french horn section', 'bassoon', 'kick drum', 'clarinet', 'viola section', 'string section', 'mandolin', 'brass section', 'glockenspiel', 'yangqin', 'cello section', 'bongo', 'horn section', 'castanet', 'banjo', 'zhongruan', 'cymbal', 'guzheng', 'violin section', 'toms', 'clarinet section', 'oud', 'auxiliary percussion', 'electric piano', 'chimes', 'claps', 'vocalists', 'erhu', 'alto saxophone', 'distorted electric guitar', 'Main System', 'bass clarinet', 'cello', 'tack piano', 'doumbek', 'electronic organ', 'bamboo flute', 'bass drum', 'acoustic guitar', 'oboe']

# raw mixing-secrets tags
classes = ['glockenspiel', 'boom', 'electrochoir', 'stringspizz', 'drum set', 'acoustic guitar reverse', 'ambmono', 'electropercussion', 'rimshot', 'vinylnoise', 'violin samples', 'rim', 'timbale', 'amomono', 'frenchhorn', 'samplechoir', 'violins', 'fx/processed sound', 'shakers', 'leadvoxdouble', 'keys', 'saxophone', 'bells', 'male speaker', 'spot_highstrings', 'marimba', 'strings_staccato', 'pad', 'sprinkles', 'handclap', 'cello', 'ukelele', 'spot_lowstrings', 'male singer', 'bongo', 'guasa', 'ambstereo', 'bombo', 'string section', 'female speaker', 'horns', 'distorted electric guitar samples', 'electric bass', 'shaker', 'harpharmonics', 'basssub', 'congas', 'maracas', 'clean electric guitar samples', 'electric piano', 'paliteo', 'tubularbells', 'bongos', 'elecnoise', 'main system', 'piano', 'subdrop', 'brushes', 'pianodry', 'cellos', 'dobro', 'conga', 'violin', 'taiko', 'samplebrass', 'gtr', 'bass synth', 'transition', 'harp sample', 'subbass', 'leadvoxdt', 'vocalists', 'roman wardrum', 'ambience', 'electronic organ', 'acousticgtr', 'mandolin', 'clean electric guitar reverse', 'female singer sample', 'malaysiandjembe', 'anvil', 'distorted electric guitarrevfx', 'wineglasses', 'tuba', 'scream', 'double bass', 'clarinet', 'violas', 'male screamer', 'harmonica', 'acoustic guitar', 'tambourine', 'distorted electric guitar', 'cunono', 'noise', 'schoolbell', 'strings_ensemble', 'fiddle', 'accordion', 'gangs', 'feedback', 'basspod', 'synthesizer', 'bass samples', 'harp', 'claps', 'sitar', 'bassdi', 'ebow', 'break', 'djembefx', 'clav', 'gongroll', 'djembe', 'tamb', 'strings_soli', 'triangle', 'handbells', 'stringpad', 'brushkit', 'bass', 'daiko', 'tub', 'trumpet', 'viola', 'leadvox', 'viola samples', 'male rapper', 'hit', 'rainstick', 'accordian', 'female singer', 'psaltery', 'click', 'cello samples', 'backingvox', 'wurlitzer', 'flute', 'clavinet', 'sample', 'tubas', 'drum machine', 'percussion', 'mellotron', 'kalimba', 'trombone', 'sidestick', 'clean electric guitar', 'woodblock', 'electrohit', 'clap']

class_dict = {}
for clss in classes:
    class_dict[clss] = []

with open("empty_yaml.yaml", 'w+') as f:
            yaml.dump(class_dict, f, indent=2, default_flow_style=False)