# Spock Version: v2.4.2
# Machine FQDN: aim-tmp.spsc.tugraz.at
# Python Executable: /home/TUG/hbradl-tug/miniconda3/envs/cuda10/bin/python
# Python Version: 3.7.11
# Python Script: /srv/user/TUG/hbradl-tug/instrument-recognition/src/training/train.py
# Run Date: 2022-03-14
# Run Time: 17:03:41
# Run w/ Docker: False
# Run w/ Kubernetes: False
# Git Branch: main
# Git Commit: c13334e662adf5f4779d32804aff88f04a6c04fc
# Git Date: 2022-03-11 16:02:05+01:00
# Git Status: DIRTY
# Git Origin: git@git.spsc.tugraz.at:hbradl/instrument-recognition.git

AugmentationConfig:
  p_augment: 0.5
  p_highshelf_filter: 0.6
  p_imp_res: 0.0
  p_lowshelf_filter: 0.6
  p_peaking_filter: 0.6
  p_pitch_shift: 0.7
  p_rand_gain: 0.8
  p_time_stretch: 0.3
DataConfig:
  data_path: /srv/ALL/datasets/preprocessed/
  dataset: jamendo
  jamendo_classes:
  - genre_downtempo
  - genre_ambient
  - genre_rock
  - instrument_synthesizer
  - genre_atmospheric
  - genre_indie
  - instrument_electricpiano
  - genre_newage
  - instrument_strings
  - instrument_drums
  - instrument_drummachine
  - genre_techno
  - instrument_guitar
  - genre_alternative
  - genre_easylistening
  - genre_instrumentalpop
  - genre_chillout
  - genre_metal
  - mood/theme_happy
  - genre_lounge
  - genre_reggae
  - genre_popfolk
  - genre_orchestral
  - instrument_acousticguitar
  - genre_poprock
  - instrument_piano
  - genre_trance
  - genre_dance
  - instrument_electricguitar
  - genre_soundtrack
  - genre_house
  - genre_hiphop
  - genre_classical
  - mood/theme_energetic
  - genre_electronic
  - genre_world
  - genre_experimental
  - instrument_violin
  - genre_folk
  - mood/theme_emotional
  - instrument_voice
  - instrument_keyboard
  - genre_pop
  - instrument_bass
  - instrument_computer
  - mood/theme_film
  - genre_triphop
  - genre_jazz
  - genre_funk
  - mood/theme_relaxing
  loudn_threshold: -40
  max_num_sources: 5
  min_num_sources: 3
  model_input_length: 4
  multitrack_classes:
  - voice
  - percussion
  - plucked-str
  - bowed-str
  - woodwind
  - brass
  - keys
  - artificial
  - drums
  - piano
  - a-guitar
  - e-guitar
  - e-bass
  - contrabass
  - sax
  - flute
  - organ
  - synth
  p_medleydb: 0.34
  p_mixingsecrets: 0.33
  p_multiple_songs: 0.35
  p_single_source: 0.35
  p_skip_percussion: 0.5
  p_skip_plucked_str: 0.5
  p_slakh: 0.33
  rms_threshold: -50
  samplerate: 32000
ModelConfig:
  model_type: short
  n_channels: 128
  n_class: 50
  n_fft: 512
  n_mels: 128
TestConfig:
  chunks_per_track: 16
  medleydb_num_singlesources: 0
  medleydb_num_submixes: 75
  mixingsecrets_num_singlesources: 0
  mixingsecrets_num_submixes: 75
  model_load_path: ./../../models/cudnn-deterministic-2/best_model.pth
  p_tensorboard: 0.08
  slakh_num_singlesources: 0
  slakh_num_submixes: 75
  tensorboard: true
TrainConfig:
  base_lr: 0.0001
  batch_size: 16
  classifier_lr: 0.0001
  freeze_base_layers: false
  log_step: 10
  lr_scheduler_gamma: 0.3
  lr_scheduler_stepsize: 20
  model_load_path: .
  model_save_path: ./../../models/pretrained/shortchunkCNN
  n_epochs: 200
  num_workers: 16
  rand_seed: 444
  train_mode: from_scratch
  weight_decay: 0.0001
ValidConfig:
  chunks_per_track: 16
  medleydb_num_singlesources: 0
  medleydb_num_submixes: 68
  mixingsecrets_num_singlesources: 0
  mixingsecrets_num_submixes: 68
  slakh_num_singlesources: 0
  slakh_num_submixes: 68
